### ISSUE TITLE
New agar.io version (550) disconnects agar.io client

### ISSUE THREAD

**Issue by l0oky** [pulviscriptor/agario-client#10]
Looks like key length has changed. It was working perfectly yesterday, they made a new version.

Here's the example.js stack trace.

```
$ node ./node_modules/agario-client/example.js
worker: client created
Requesting server in region EU-London
HTTP request answer: 139.162.198.65:443
36XyMmbZ

Connecting to ws://139.162.198.65:443
worker: connecting...
worker: connected to server
worker: disconnected
worker: spawning
c:\projects\nodejs\agario-dinner-bot\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:214
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (c:\projects\nodejs\agario-dinner-bot\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:214:16)
    at Object.Client.send (c:\projects\nodejs\agario-dinner-bot\node_modules\agario-client\agario-client.js:130:17)
    at Object.Client.spawn (c:\projects\nodejs\agario-dinner-bot\node_modules\agario-client\agario-client.js:415:14)
    at Object.<anonymous> (c:\projects\nodejs\agario-dinner-bot\node_modules\agario-client\example.js:55:12)
    at Object.emit (events.js:104:17)
    at null._onTimeout (c:\projects\nodejs\agario-dinner-bot\node_modules\agario-client\agario-client.js:88:20)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by l0oky** [comment]
Never mind, looks like the new version of agario-client fixed it. Keep up the good work #pulviscriptor!

**Comment by pulviscriptor** [comment]
It is fixed for now. Author of agar.io replaced `buf.setUint32(1, 673720361, true);` with `buf.setUint32(1, 2207389747, true);` and this is (I think) to kill all unofficial clients.
Let's hope he will not do this every day.
