### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by thisismo** [pulviscriptor/agario-client#121]
/root/fix/node_modules/ws/lib/WebSocket.js:218
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/root/fix/node_modules/ws/lib/WebSocket.js:218:16)
    at Object.Client.send (/root/fix/node_modules/agario-client/agario-client.js:179:17)
    at Object.Client.onConnect (/root/fix/node_modules/agario-client/agario-client.js:92:14)
    at WebSocket.onOpen (/root/fix/node_modules/ws/lib/WebSocket.js:432:14)
    at WebSocket.emit (events.js:104:17)
    at WebSocket.establishConnection (/root/fix/node_modules/ws/lib/WebSocket.js:862:8)
    at ClientRequest.upgrade (/root/fix/node_modules/ws/lib/WebSocket.js:753:25)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:118:17)
    at Socket.socketOnData (_http_client.js:349:11)

**Comment by pulviscriptor** [comment]
First of all - this is bug in `ws` library https://github.com/websockets/ws/issues/669 crash 2
<b>BUT!</b>
I made check for it https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L88
What version of `agario-client` you use? Is it outdated?

**Comment by thisismo** [comment]
no i just fixed it with the websockets/ws#669 thanks

**Comment by thisismo** [comment]
/root/fix/node_modules/agario-client/agario-client.js:172
            throw err;
                  ^
Error: ws bug #669:crash2 detected, `onopen` called with not established connection
    at Object.Client.onConnect (/root/fix/node_modules/agario-client/agario-client.js:89:49)
    at WebSocket.onOpen (/root/fix/node_modules/ws/lib/WebSocket.js:432:14)
    at WebSocket.emit (events.js:104:17)
    at WebSocket.establishConnection (/root/fix/node_modules/ws/lib/WebSocket.js:862:8)
    at ClientRequest.upgrade (/root/fix/node_modules/ws/lib/WebSocket.js:753:25)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:118:17)
    at Socket.socketOnData (_http_client.js:349:11)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
New error i'm getting with this code

**Comment by thisismo** [comment]
Btw I'm using the fixed ws

**Comment by pulviscriptor** [comment]
You need to catch `client.on.packetError` event and call `preventCrash()`. Check readme.

**Comment by thisismo** [comment]
oh yes thanks, my mistake.
