### ISSUE TITLE
strange

### ISSUE THREAD

**Issue by mogokcp** [pulviscriptor/agario-client#126]
/home/server/node_modules/agario-client/agario-client.js:528
                throw e;
                      ^
TypeError: Cannot read property 'name' of undefined
    at /home/server/feeder.js:151:49
    at Array.map (native)
    at Object.<anonymous> (/home/server/feeder.js:150:38)
    at Object.g (events.js:180:16)
    at Object.emit (events.js:106:17)
    at Object.Client.emitEvent (/home/server/node_modules/agario-client/agario-client.js:525:23)
    at Client.processors.49 (/home/server/node_modules/agario-client/agario-client.js:411:20)
    at Object.Client.onMessage (/home/server/node_modules/agario-client/agario-client.js:154:13)
    at WebSocket.onMessage (/home/server/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:98:17)
 

helppp

**Comment by mogokcp** [comment]
Switched to previous version, now i get

"Killed"

and script stop

**Comment by pulviscriptor** [comment]
>TypeError: Cannot read property 'name' of undefined
>at /home/server/feeder.js:151:49

Check that line.

**Comment by agarioBotDev** [comment]
@mogokcp seems likeyou try to acces property name before you defined the ball

**Comment by agarioBotDev** [comment]
@mogokcp Edit: or it is a virus, that has no name. do:

```javascript
if (ball.virus) {continue;}
```

**Comment by hassanila97** [comment]
easy, just edit the code to check if undefined before .name

**Comment by pantshobhit** [comment]
hey

**Comment by pantshobhit** [comment]
somebody please help me

**Comment by pantshobhit** [comment]
i am getting the same error can anyone please specify what i have to do to resolve it?
![error](https://cloud.githubusercontent.com/assets/17199226/14405809/35e6685e-feb4-11e5-8b72-2998b5971fdf.png)

**Comment by pantshobhit** [comment]
just forget the key thing-warning it has been resolved

**Comment by pulviscriptor** [comment]
@pantshobhit 
Problem is in `feeder.js` which is some third party code not related to this repository. 
Try this one https://github.com/davidmann4/ogar-feeder-bot/issues
