### ISSUE TITLE
Packet issues while using agario-client with proxies

### ISSUE THREAD

**Issue by agarsearcher1985** [pulviscriptor/agario-client#147]
Hey,
I get 2 types of errors if I use agario-client with proxies.
**Error type A **(almost only with https-proxy-agent):
```
Bot 8: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 8: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 98: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
Bot 82: [warning] unknown packet ID(0): 00 4c 00 6f 00 6c 00 5e 00 5e 00
```
**Error type B **(https-proxy-agent and agent via socks):
```
/path/to/my/server/files/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode
    at WebSocket.onError (/path/to/my/server/files/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (/path/to/my/server/files/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/path/to/my/server/files/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/path/to/my/server/files/node_modules/ws/lib/Receiver.js:212:12)
    at Receiver.add (/path/to/my/server/files/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/path/to/my/server/files/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Thanks for your help :)

**Comment by pulviscriptor** [comment]
Error type B is an old bug in `ws` library which was fixed in repo https://github.com/websockets/ws/pull/681 but NPM package is not updated. You can fix it like it fixed in that PR.
Error A is something strange. There is no Server->Client packet ID 0, only Client->Server which means "Spawn with nickname" and your packets have nickname `Lol^^` in them. But how did they got received by client. Is that your nickname? How often you see these warnings? 
If anybody else saw this warning `unknown packet ID(0)` please report it here.

**Comment by agarsearcher1985** [comment]
I receive this warning often. Usually the client crashs, but I implemented the preventCrash and added this debug line. I'll test it with the new ws version, thx.

**Comment by hassanila97** [comment]
SAME WARNING

**Comment by agarsearcher1985** [comment]
Ok, ws update fixed the crash issue. Warning is still there. Hopefully anyone knows why they appear.

**Comment by pulviscriptor** [comment]
I'd like to know if warning is still there. Does anybody see it? Does that packet contains your nickname?

**Comment by hassanila97** [comment]
I dont see it anymore
