### ISSUE TITLE
"Value out of bounds" - Auth Token issue

### ISSUE THREAD

**Issue by DeltaEnemy** [pulviscriptor/agario-client#154]
Hi, i got this error when i use auth-token:

buffer.js:784
    throw TypeError('value is out of bounds');
    ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeUInt8 (buffer.js:794:5)
    at Object.Client.onConnect (/root/EnemyBot/node_modules/agario-client/agario-client.js:115:21)
    at WebSocket.onOpen (/root/EnemyBot/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:456:14)
    at WebSocket.EventEmitter.emit (events.js:92:17)
    at WebSocket.establishConnection (/root/EnemyBot/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:887:8)
    at ClientRequest.upgrade (/root/EnemyBot/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:778:25)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:106:17)
    at Socket.socketOnData (http.js:1612:11)

**Comment by pulviscriptor** [comment]
As i see its some problem in PR https://github.com/pulviscriptor/agario-client/pull/130/files code
Can you please show example of token that you use (delete/change some symbols in it so it will not get stolen) to reproduce crash.

**Comment by DeltaEnemy** [comment]
I have an array of 200 tokens, a lot of them work, but some gives this crash... This is a example:

CAAJoMBwWJiMBAIndm4WuIRRCMMhphmQJsIAEZAwVLKJr7NXMzKu8lcNyV6ZAxw3PZBZBBkqAsnZB7ogOZBDa2RBVR1PhoPUK6RyLZAWZCoqlP2rW7eQiWSd1OZByWeeTw7D0G8tRXO7wUDTNjjY8SE48p2kP88HRxTW7Xo7CZBMk2Hs0rfHc0l9p23J5tAo6e4IdCMbuAsZBwURGsHg4YESDOQU

**Comment by pulviscriptor** [comment]
I tested token that you posted and it is not causing crash.
Can you test tokens in `basic.js` and if it will crash then show them, because i think you setting `client.auth_token` to something strange with symbols that should not be there.
`client.auth_token = '♕♚♛⚜★☆✮✯☄☾☽☼☀☁☂☃☻☺☹۞۩';` will cause that crash, but this is invalid token.
If you do use valid tokens and they crashing, please show one.

**Comment by DeltaEnemy** [comment]
Ok, I generated the tokens again and is no longer crashing... You can close this Issue.
Thanks for help!

**Comment by Nick8fr32** [comment]
do u have 200 fb acc??? @DeltaEnemy

**Comment by tweenkapy** [comment]
@Nick8fr32 Its a cookie stealer, easy to make it

**Comment by Nick8fr32** [comment]
can u help me with it???
