### ISSUE TITLE
Returns Error On Party Mode Connect

### ISSUE THREAD

**Issue by Sonicmaster13** [pulviscriptor/agario-client#30]
Greetings, 
   Whenever i connect to a party mode server using this script, specifying the ip AND key, after a bit of time, i get this error: 

buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
    ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt16LE (buffer.js:609:5)
    at Object.Packet.readUInt16LE (/home/mrsonic/agarclient/packet.js:51:29)
    at Client.processors.16 (/home/mrsonic/agarclient/spawnIn().js:234:39)
    at Object.Client.onMessage (/home/mrsonic/agarclient - FINAL/AgarioClient.js:129:9)
    at WebSocket.onMessage (/home/mrsonic/agarclient FINAL/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.onbinary (/home/mrsonic/RSAgarBots - FINAL/node_modules/ws/lib/WebSocket.js:823:10)
    at /home/mrsonic/agarclient/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/home/mrsonic/agarclient/node_modules/ws/lib/Receiver.js:364:5)
    at /home/mrsonic/agarclient/node_modules/ws/lib/Receiver.js:531:14

Any help is appriciated!

**Comment by pulviscriptor** [comment]
Hi.
Sorry for slow answer.
I can not reproduce your issue.
Please check that `npm list agario-client` shows `agario-client@1.1.2`. 
If your version less than 1.1.2 then do `npm update agario-client`.

**Comment by Sonicmaster13** [comment]
Its ok
I do have the latest version
I have found out that the error lies in the agario-client.js, wherever it says anything related to UInt
I know this is with the packets, but i don't know why i get it i have looked everywhere.

**Comment by Sonicmaster13** [comment]
Ok, apparently NPM was lying, i looked manually, and i was 2 versions off. Updated files, will test now. I have my fingers crossed.

**Comment by Sonicmaster13** [comment]
Fixed.
