### ISSUE TITLE
Disconnect() error

### ISSUE THREAD

**Issue by Sonicmaster13** [pulviscriptor/agario-client#38]
Whenever you try to pass the disconnect() function it gives this error:

       this.ws.close();
               ^

    TypeError: Cannot read property 'close' of undefined
    at Object.Client.disconnect (C:\Users\clock\node_modules\agario-client\agario-client.js:61:16)
    at Object.<anonymous> (C:\Users\clock\node_modules\agario-client\examples\basic.js:130:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

All i did was, after doing npm update to be sure, add a client.disconnect();  to the basic.js; it returned this error, so its NOT my api, its a problem with the lib. I have looked, and i don't see anything to be causing this in the lib. I tried this.close(); instead of this.ws.close() because i saw other this.send(); things. That did not work, and ws.close(); obviously would not work.

**Comment by pulviscriptor** [comment]
This is an issue and i will fix crash. 
But looks like you calling `disconnect()` before calling `connect()` so my fix will not help you probably.

**Comment by Sonicmaster13** [comment]
No, i have not called disconnect() before connect() that would give another error.

**Comment by pulviscriptor** [comment]
It may be bug somewhere else, but this code
```javascript
var AgarioClient = require('agario-client');
var client = new AgarioClient('worker');
client.disconnect();
```
Causes exact same crash (before this fix)
If this is not the case, please provide steps to reproduce your crash.
