### ISSUE TITLE
RangeError: index out of range  (Please answer me fast thanks :)

### ISSUE THREAD

**Issue by DarkSaTla** [pulviscriptor/agario-client#87]
hey when i started my bots in 10 - 20 min i get crashed...
C:\Users\agario\node_modules\agario-client\agario-client.js:166
            throw err;
                  ^
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt8 (buffer.js:544:5)
    at Object.Packet.readUInt8 (C:\Users\agario\node_modules\agario-client\packe
t.js:25:29)
    at Client.processors.16 (C:\Users\agario\node_modules\agario-client\agario-c
lient.js:256:38)
    at Object.Client.onMessage (C:\Users\agario\node_modules\agario-client\agari
o-client.js:148:13)
    at WebSocket.onMessage (C:\Users\agario\node_modules\agario-client\node_modu
les\ws\lib\WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (C:\Users\agario\node_modules\agario-client\node_module
s\ws\lib\WebSocket.js:823:10)
    at C:\Users\agario\node_modules\agario-client\node_modules\ws\lib\Receiver.j
s:537:18
    at Receiver.applyExtensions (C:\Users\agario\node_modules\agario-client\node
_modules\ws\lib\Receiver.js:364:5)

how i can fix it please answer me..

**Comment by pulviscriptor** [comment]
Check https://github.com/pulviscriptor/agario-client/issues/46#issuecomment-169786276

**Comment by davidmann4** [comment]
https://github.com/davidmann4/agario-feeder-bot/issues/170#issuecomment-183461033

**Comment by davidmann4** [comment]
ahh I've to add

```javascript
bot.on('packetError', function(packet, err, preventCrash) {
   bot.log('Packet error detected for packet: ' + packet.toString());
   bot.log('Crash will be prevented, bot will be disconnected');
   preventCrash();
   bot.disconnect();
});`
```

**Comment by davidmann4** [comment]
works
