### ISSUE TITLE
Getting a lot of Packet error detected for packet: errors with Ogar Server

### ISSUE THREAD

**Issue by davidmann4** [pulviscriptor/agario-client#90]
any Idea whats up with the errors I receive after the client update?

I use my Ogar server which basically did not changed at all but I get this packet errors: 
Bot_1: Packet error detected for packet: 40 00 00 00 00 80 9f c5 40 00 00 00 00 00 38 9a 40 00 00 00 00 c0 ab d0 40 00 00 00 00 00 fe bd 40

makes no sense to me since the server is still the same...

**Comment by davidmann4** [comment]
![image](https://cloud.githubusercontent.com/assets/1736570/13158862/3b2ea396-d68f-11e5-9310-0d5dc53b1a49.png)

**Comment by thisismo** [comment]
same here, none of my bots are even connecting, using the same script. I'm always getting a negotiation error.

**Comment by davidmann4** [comment]
packets of other people:
40 f4 2d cf d6 2c 35 97 40 26 c4 d6 0f 0c f1 a4 c0 b0 ac 26 6c 7d 7c bb 40 64 ef a4 c0 cf 7b 81 40
40 5f 95 a4 5e 0d 2c c0 c0 02 0d c2 87 be f9 bb c0 ce 98 19 af e4 02 b1 c0 05 1a 84 0f 7d a3 ae c0

**Comment by pulviscriptor** [comment]
@davidmann4 
Can you show error's trace? Because 0x40 = 64 = mapSizeLoad https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L427
And i don't see error there
```javascript
var packet = new AgarioClient.Packet(new Buffer([
    0x00, 0x00, 0x00, 0x00, 0x80, 0x9f, 0xc5, 0x40,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x38, 0x9a, 0x40,
    0x00, 0x00, 0x00, 0x00, 0xc0, 0xab, 0xd0, 0x40,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xfe, 0xbd, 0x40]));

console.log(packet.readFloat64LE());
console.log(packet.readFloat64LE());
console.log(packet.readFloat64LE());
console.log(packet.readFloat64LE());
```
>11071
1678
17071
7678

**Comment by davidmann4** [comment]
how I can output the error trace?

https://github.com/davidmann4/ogar-feeder-bot/blob/master/feeder.js#L186

**Comment by pulviscriptor** [comment]
@davidmann4 
```javascript
        bot.client.on('packetError', function(packet, err, preventCrash) {
           bot.log('Packet error detected for packet: ' + packet.toString());
           bot.log('Crash will be prevented, bot will be disconnected, stack trace:\r\n' + err.stack);
           preventCrash();
           bot.client.disconnect();
        });
```

**Comment by WJKH** [comment]
Same issue here.

```
Bot_1: Connection Success, spawning
Bot_1: Packet error detected for packet: 40 17 0b 5b c2 95 ee c0 c0 fd dd 06 13 21 cd be c0 d2 8a 86 33 f7 60 b5 40 03 c3 35 a5 01 71 b8 40 00 00 00 00 31 00 2e 00 33 00 2e 00 39 00 00 00
Bot_1: Crash will be prevented, bot will be disconnected, stack trace:
ReferenceError: map_max_x is not defined
    at Object.<anonymous> (/home/afeeder/AFB/F1/feeder.js:111:36)
    at Object.emit (events.js:118:17)
    at Client.processors.64 (/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:436:20)
    at Object.Client.onMessage (/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:154:13)
    at WebSocket.onMessage (/home/afeeder/AFB/F1/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/home/afeeder/AFB/F1/node_modules/ws/lib/WebSocket.js:823:10)
    at /home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:364:5)
    at /home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:531:14
Bot_1: New Cell Generated (3369061)
Bot_1: Packet error detected for packet: 40 6d 37 a8 c1 bd de b3 40 d1 51 eb 64 35 a5 be 40 9e b1 2a 01 36 6a c0 40 06 ac 23 0b fb 6a c5 40
Bot_1: Crash will be prevented, bot will be disconnected, stack trace:
ReferenceError: map_max_x is not defined
    at Object.<anonymous> (/home/afeeder/AFB/F1/feeder.js:111:36)
    at Object.emit (events.js:118:17)
    at Client.processors.64 (/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:436:20)
    at Object.Client.onMessage (/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:154:13)
    at WebSocket.onMessage (/home/afeeder/AFB/F1/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/home/afeeder/AFB/F1/node_modules/ws/lib/WebSocket.js:823:10)
    at /home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:364:5)
    at /home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:531:14
Bot_1: Server Leaderboard: HUN-BEN - JnPau BrHi - spy - unnamed - sid - kkkkkkkkkkkkkkk - Tunisia - Jumbo - DION - 3tewni tissa3
Bot_1: Disconnected from the server.
```

**Comment by pulviscriptor** [comment]
>ReferenceError: map_max_x is not defined
    at Object.<anonymous> (/home/afeeder/AFB/F1/feeder.js:111:36)

Here is your problem https://github.com/davidmann4/ogar-feeder-bot/blob/master/feeder.js#L111
But i didn't know that crashed even emitter will crash processor. Now we all know.

**Comment by WJKH** [comment]
Alright @pulviscriptor just checked it recently and line 111 and 112 is the problem.
@davidmann4 you forget bot. before map_max_x and etc. as far as I can see.

**Comment by davidmann4** [comment]
ohh, funny
